AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ImageLabelsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "ImageLabels"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: "Project"
          Value: "AWS Image Processing"
